Manipulando array

In [ ]:
# ARRAY Y RESHAPE

import numpy as np

a= np.array([1,2,3,4,5,6])
b= np.reshape(a, (3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


Arrays unidimensionales

In [ ]:
# ACCESO A LOS VALORES DE UN ARRAY

import numpy as np

ejemplo_1= np.array([10,11,12,13,14,15])
print(ejemplo_1[2]) #accedo a la posición 2 de mi array
print(ejemplo_1[-3]) #accedo a la posición -3 de mi array


# MODIFICACIÓN DE UN VALOR DENTRO DE UN ARRAY

ejemplo_2= np.array([10,11,12,13,14,15])
ejemplo_2[0]= ejemplo_2[1] + ejemplo_2[5] #la posición 0 va a ser la suma de los elementos en la posición 1 + 5
print(ejemplo_2)


# BORRADO DE VALORES DE UN ARRAY / DELETE

ejemplo_3= np.array([10,11,12,13,14,15])
ejemplo_3= np.delete(ejemplo_3, 2) #indice como escalar, se elimina el elemento de la posición 2
print(ejemplo_3)

ejemplo_4= np.array([10,11,12,13,14,15])
ejemplo_4= np.delete(ejemplo_4, (2,3,4)) #indice como tupla, elimina el elemento de la posición 2 y 3
print(ejemplo_4)


# INSERCIÓN DE NUEVOS VALORES EN UN ARRAY / APPEND E INSERT

ejemplo_5= np.array([10,11,12,13,14,15])
ejemplo_5= np.append(ejemplo_5, 16) #con append añade elementos hacia el final
print(ejemplo_5)

ejemplo_6= np.array([10,11,12,13,14,15])
ejemplo_6= np.insert(ejemplo_6, 1, 101) #con insert añade elementos en una posición determinada
print(ejemplo_6)



12
13
[26 11 12 13 14 15]
[10 11 13 14 15]
[10 11 15]
[10 11 12 13 14 15 16]
[ 10 101  11  12  13  14  15]


Arrays multidimensionales

In [ ]:
import numpy as np

values_1= np.arange(1, 13).reshape(3, 4)  #arange de elementos entre 1 y 13 / reshape convierto a multidimensional de 3 filas x 4 columnas
print(values_1)


# ACCEDO A ELEMENTOS INDIVIDUALES

a= values_1[0, 0] #accedo a la posición 0 de la fila 0
print(a)

b= values_1[-1, -1] #accedo a la posición -1 de la fila -1
print(b)

c= values_1[1, 2] #accedo a la fila 1 de la posición o elemento 2
print(c)

# ACCESO A MÚLTIPLES ELEMENTOS

d= values_1[[0, 2], [1, 2]] #1)accedo a fila 0 columna 1 (2), 2)accedo a fila 2 columna 2(11)
print(d)

# ACCESO A FILAS O COLUMNAS COMPLETAS

e= values_1[2] #accedo a toda la tercera fila
print(e)

f= values_1[:, 1]#accedo a toda la segunda columna
print(f)

# ACCESO A ZONAS PARCIALES DEL ARRAY

g= values_1[0:2, 0:2] # accedo a las filas desde la 0 hasta la 2 y columnas desde la 0 hasta la 2
print(g)

h= values_1[0:2, [1, 3]] # accedo a las filas desde la 0 hasta la 2 y los valores de la columna 1 y valores de la columna en 3
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
12
7
[ 2 11]
[ 9 10 11 12]
[ 2  6 10]
[[1 2]
 [5 6]]
[[2 4]
 [6 8]]


Modificación de Arrays multidimensionales

In [ ]:
# MODIFICACIÓN

import numpy as np

values= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
values= np.reshape(values, (3,4))
print(values)

print()

values[0,0]=100
print(values)

print()

values[1]= [55,66,77,88] #modifico toda la fila 1
print(values)

print()

values[:,2]= [30,70,110]  # con : por defecto comienza en fila 0 y columna 2
print(values)

print()


# BORRADO

values= np.delete(values, 0, axis=0)  #borrado de la primera fila / el axis = 0 indica sobre fila
print(values)

print()

values= np.delete(values, (1,3), axis=1) # borrado de la segunda y cuarta columna
print(values)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

[[100   2   3   4]
 [ 55  66  77  88]
 [  9  10  11  12]]

[[100   2  30   4]
 [ 55  66  70  88]
 [  9  10 110  12]]

[[ 55  66  70  88]
 [  9  10 110  12]]

[[ 55  70]
 [  9 110]]


Añadir elementos en arrays multidimensionales

In [ ]:
# AÑADIR AL FINAL CON APPEND

import numpy as np

values= np.array([1,2,3,4])
values= np.reshape(values, (2,2))
print(values)

print()

values= np.append(values, [[5, 6]], axis= 0) #añade hacia el final 5 y 6 como nueva fila con axis = 0
print(values)

print()

values= np.reshape(values, (2,3)) #actualizo el tamaño de mi array multidimensional para lograr la siguiente linea
values= np.append(values, [[5], [6]], axis= 1) # agrego 5 y 6 hacia el final como columna con axis = 1
print(values)

print()

# INSERTAR EN UNA POSICIÓN ARBITRARIA


values_2= np.array([1,2,3,4])
values_2= np.reshape(values_2, (2,2))
print(values_2)

print()

values_2= np.insert(values_2, 0, [0, 0], axis= 0) # agrego en la posición 0 (fila) los valores 0 y 0 en filas por el axis= 0
print(values_2)

print()

values_2= np.reshape(values_2, (2,3)) #actualizo tamaño de mi array multidimensional
values_2= np.insert(values_2, 1, [0, 0], axis= 1) #agrego en la posicion 1(columna) los valores 0 y 0 en columna 1 por el axis= 1
print(values_2)


[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3 5]
 [4 5 6 6]]

[[1 2]
 [3 4]]

[[0 0]
 [1 2]
 [3 4]]

[[0 0 0 1]
 [2 0 3 4]]


Combinar dos o más matrices: hay veces que nos interesa combinar dos matrices(arrays en general). Una de los mecanismos que nos proporciona NumPy es el apilado.

In [ ]:
# APILADO VERTICAL
# VSTACK

import numpy as np

m1= np.random.randint(1, 100, size=(3,2)) # randint numero aleatorio entre 1 y 100 con un tamaño de 3 filas por 2 columnas
print(m1)

print()

m2= np.random.randint(1, 100, size=(1,2)) # randint numero aleatorio entre 1 y 100 con un tamaño de 1 fila y 2 columnas
print(m2)

print()

m1_m2= np.vstack((m1, m2)) #combino matrices m1 y m2 con vstack, apilado verticalmente
print(m1_m2)

[[11 77]
 [81 60]
 [57 45]]

[[65 80]]

[[11 77]
 [81 60]
 [57 45]
 [65 80]]


In [ ]:
# APILADO HORIZONTAL
# HSTACK

import numpy as np

m3= np.random.randint(1, 100, size=(3, 2))
print(m3)

print()

m4= np.random.randint(1, 100, size=(3,1))
print(m4)

print()

m3_m4= np.hstack((m3, m4)) # #combino matrices m3 y m4 con hstack, apilado horizontalmente
print(m3_m4)


[[23 68]
 [ 7 42]
 [31 10]]

[[97]
 [13]
 [ 8]]

[[23 68 97]
 [ 7 42 13]
 [31 10  8]]


Repetición de elementos: repetición por ejes, el parámetro de repetición indica el número de veces que repetimos el array completo por cada eje.

In [ ]:
# TILE

values= np.array([[1,2],[3,4],[5,6]])
#values= np.reshape(values, (2,2))
print(values)

print()

values= np.tile(values, 3) # repite por defecto lo reconoce por 3 columnas
print(values)

print()

values= np.tile(values, (2,3)) # repite por 2 filas y 3 columnas
print(values)

[[1 2]
 [3 4]
 [5 6]]

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [5 6 5 6 5 6]]

[[1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [5 6 5 6 5 6 5 6 5 6 5 6 5 6 5 6 5 6]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [5 6 5 6 5 6 5 6 5 6 5 6 5 6 5 6 5 6]]


Repetición de elementos: el parámetro de repetición indica el número de veces que repetimos cada elementos del array

In [ ]:
# REPEAT

values= np.array([[1,2],[3,4],[5,6]])
print(values)

print()

values= np.repeat(values, 2) # el 2 es el parámetro de veces que quiero repetir cada elemento
print(values)

print()

values= np.repeat(values, 2, axis= 0) #repite por 2 en filas
print(values)

print()

values= np.repeat(values, 3, axis= 1) #repite por 3 en columnas
print(values)

[[1 2]
 [3 4]
 [5 6]]

[1 1 2 2 3 3 4 4 5 5 6 6]

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]



AxisError: ignored

Extracción de los elementos de la diagonal: la función np.diag() permite acceder a los elementos de un array especificando un parámetro k que indica 'distancia' con la diagonal principal.

In [ ]:
# DIAG

import numpy as np

values = np.array([[73,86,90,20],[96,55,15,48],[38,63,96,95],[13,87,32,96]])
print(values)

print()

values_1 = np.diag(values) # con DIAG k = 0
print(values_1)

print()

for k in range(1, values.shape[0]): #
  print(f'k={k}', np.diag(values, k=k)) #imprime k1 diagonal medio k2 diagonal siguiente k3 diagonal siguiente hacia arriba

print()

for k in range(1, values.shape[0]): #
  print(f'k={k}', np.diag(values, k=-k)) #imprime a la inversa


[[73 86 90 20]
 [96 55 15 48]
 [38 63 96 95]
 [13 87 32 96]]

[73 55 96 96]

k=1 [86 15 95]
k=2 [90 48]
k=3 [20]


Modificación de los elementos de la diagonal: con la función np.diag_indices() retorna los indices de los elementos de la diagonal principal, con lo que podemos modificar sus valores directamente.

In [ ]:
# DIAG_INDICES

import numpy as np

values = np.array([[73,86,90,20],[96,55,15,48],[38,63,96,95],[13,87,32,96]])
print(values)

print()

di= np.diag_indices(values.shape[0]) #me muestra la cantidad de elementos de mi diagonal y vertical
print(di)

print()

values[di]= 0 #convierto en cero mi diagonal principal, puede ser 0 como cualquier número
print(values)

# TRIU_INDICES indices de mi diagonal superior

# TRIL_INDICES  indices de mi diagonal inferior

[[73 86 90 20]
 [96 55 15 48]
 [38 63 96 95]
 [13 87 32 96]]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

[[ 0 86 90 20]
 [96  0 15 48]
 [38 63  0 95]
 [13 87 32  0]]
