

Operaciones Lógicas: El indexado booleano es una operación que permite conocer a nivel elemento si un array cumple o no con una determinada condición.



In [ ]:
cantLavados = int(input("Ingrese la cantidad de lavados que hace en un mes"))
costoLavadero = float(input("Ingrese el costo de cada lavado en el lavadero automático"))
precioContado = float(input("Ingrese el precio de contado del lavarropas"))

gastosLavadero = costoLavadero * cantLavados
opcionPago_6 = precioContado / 6
opcionPago_12 = (precioContado * 30 / 100 + precioContado) / 12
opcionPago_18 = (precioContado * 50 / 100 + precioContado) / 18

if gastosLavadero * 2 > opcionPago_6:
    print("Conviene comprar el lavarropas en 6 cuotas sin interés. Usted pagará por mes: ",opcionPago_6," durante 6 meses")
elif gastosLavadero * 2 > opcionPago_12 and opcionPago_12 < opcionPago_6:
    print("Conviene comprar el lavarropas en 12 cuotas. Usted pagará: ",opcionPago_12," durante 12 meses")
elif gastosLavadero * 2 > opcionPago_18 and opcionPago_18 < opcionPago_12 and opcionPago_18 < opcionPago_6:
    print("Conviene comprar el lavarropas en 18 cuotas. Usted pagará: ",opcionPago_18, " durante 18 meses")
else:
    print("Siga llevando la ropa al lavadero")

Ingrese la cantidad de lavados que hace en un mes2
Ingrese el costo de cada lavado en el lavadero automático50
Ingrese el precio de contado del lavarropas2500
Siga llevando la ropa al lavadero


In [ ]:
#INDEXADO BOOLEANO

import numpy as np

values = np.array([[73,86,90,20],[96,55,15,48],[38,63,96,95],[13,87,32,96]])
print(values)

print()

ejemplo1 = values > 50 # indexado booleano
print(ejemplo1)

print()

ejemplo2 = values[values > 50] # uso de máscara
print(ejemplo2)

print()

ejemplo3 = values[values > 50] = -1
print(ejemplo3)



[[73 86 90 20]
 [96 55 15 48]
 [38 63 96 95]
 [13 87 32 96]]

[[ True  True  True False]
 [ True  True False False]
 [False  True  True  True]
 [False  True False  True]]

[73 86 90 96 55 63 96 95 87 96]

-1


In [ ]:
# INDEXADO BOOLEANO CON CONDICIONES LÓGICAS

import numpy as np

values = np.array([[73,86,90,20],[96,55,15,48],[38,63,96,95],[13,87,32,96]])
print(values)

print()

ejemplo4 = (values < 25) | (values > 75) # | equivale a "or"
print(ejemplo4)

print()

ejemplo5 = (values > 258) & (values < 75) # & equivale a "and"
print(ejemplo5)

[[73 86 90 20]
 [96 55 15 48]
 [38 63 96 95]
 [13 87 32 96]]

[[False  True  True  True]
 [ True False  True False]
 [False False  True  True]
 [ True  True False  True]]

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


Para obtener los indices del array que satisfacen una determinada condición, NumPy nos proporciona el método **where()**

In [ ]:
# WHERE

import numpy as np

values = np.array([[73,86,90,20],[96,55,15,48],[38,63,96,95],[13,87,32,96]])
print(values)

print()

idx = np.where(values > 50) # devuelve filas y columnas
print(idx)

print()

values[idx] # devuelve los valores que cumplen mi condición

[[73 86 90 20]
 [96 55 15 48]
 [38 63 96 95]
 [13 87 32 96]]

(array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3]), array([0, 1, 2, 0, 1, 1, 2, 3, 1, 3]))



array([73, 86, 90, 96, 55, 63, 96, 95, 87, 96])

Para comparar dos arrays se puede usar el operador == del mismo modo que con cualquier otro objeto de Python. El resultado se evalúa a nivel de elemento.

In [ ]:
#EQUAL

m1 = np.array([[1,2], [3,4]])
m3 = np.array([[1,2], [3,4]])

resultado = m1 == m3 # verifica si el elemento de la primera fila/columna del array es igual al otro
print(resultado)

print()

resultado_total = np.array_equal(m1, m3) # EQUAL comparo ambos arrays en su totalidad
print(resultado_total)

[[ True  True]
 [ True  True]]

True


Operaciones sobre conjuntos: **Union**

In [ ]:
# UNION1d

x = np.array([9, 4, 11, 3, 14, 5, 13, 12, 7, 14])
y = np.array([17, 9, 19, 4, 18, 4, 7, 13, 11, 10])

union = np.union1d(x, y) #UNION de ambos conjuntos
print(union)

[ 3  4  5  7  9 10 11 12 13 14 17 18 19]


Ordenación: existen dos formas de ordenar cualquier estructura de datos, una que modifica los valores (destructiva) y otra que devuelve nuevos valores(no destructiva). En el caso de NumPy también es así.

In [ ]:
from numpy.core.multiarray import array
# SORT

import numpy as np

values= array([23,24,92,88,75,68,12,91,94,24,9,21,42,3,66]) #array unidimensional
print(values)

np.sort(values) #no destructivo, es decir, mantiene valores originales

print()

values_1=np.array([52,23,90,46,61,63,74,59,75,5,58,70,21,7,80,52])
values_2=np.reshape(values_1, (4,4))
print(values_2)

print()

np.sort(values_2, axis=1) # equivale a decir que me ordene por defecto de menor a mayor las filas

print()

column=np.sort(values_2, axis=0) # equivale a decir que me ordene por defecto de menor a mayor las columnas
print(column)



[23 24 92 88 75 68 12 91 94 24  9 21 42  3 66]

[[52 23 90 46]
 [61 63 74 59]
 [75  5 58 70]
 [21  7 80 52]]


[[21  5 58 46]
 [52  7 74 52]
 [61 23 80 59]
 [75 63 90 70]]


Contar la cantidad de valores de un array

In [ ]:
# UNIQUE, RETURN_COUNTS, COUNT_NONZERO

import numpy as np

randomized= np.random.randint(1, 11, size=1000) #
print(randomized)

print()

unique= np.unique(randomized) #unique contará los valores unicos de mi array
print(unique)

print()

unique_2= np.unique(randomized, return_counts=True) #valores únicos incluyendo la frecuencia de repetición de c/u en mi array
print(unique_2)

print()

unique_3= np.count_nonzero(randomized) #contar valores distintos del número cero
print(unique_3)

print()

unique_4= np.count_nonzero(randomized > 5) #condición lógica: contar elementos mayores a 5
print(unique_4)

[ 9  8  5  1  6  4  8  9  4  8  9  6  4  2  9  6  2  2  1  6  8  9  4  5
  3  3  5  6  2  3  1  7  4  9  7  7  4  1 10  7  2  3  9  9  8 10  9  1
  7  6  1  1  7 10  5  6  1  3  6  1  7  5  6  2 10  8  6  9  2  4  9  9
 10  4  1  2  7  1  8  9  5  9  1 10  6  9 10  5  5  2 10  3  4  3  8  1
  5  4  7  2  5  7  6 10 10 10  8  5  9  9  6  4 10  7  4  5  5  6  2  2
  2  1  1  7  7  3  6  5  5  9  2  5  9  2  3  1  5  7  3  9  8  4 10  3
  4  5  4  4  1  5  8  4  2  9  5  1 10 10  1  8  1  1 10  5  5  3  7  6
  4  3  3  7  3  2  3  4  9  2  7  4  3  1  5  8  1  4  3  4  4  2  2  8
  7  6  4  1  4  2  3  2  6  8  7  2  8  7  2  1  1  3  5 10  9  9  7  7
  6  2  4  9 10  5  8  2  3  5  3 10  7  8  6 10  8  9  1  6  5  2  3  9
  9  1  3  7  5  3  1  7  4  1  4  4  1  9  7  1  5  1  6  4  2  9  7  6
  1  5  1 10  9  5  6  7  2  7  4 10  7  4  9  9  3  5  9  3  6  1  6  5
  4  6  2  7  8 10  2  1  9  7  8  8  9  4  7  3  1  7  6 10  5  3  5 10
  9  9  9  1  6  5  7 10  4  4  4  8  1  7  1  3  4

Funciones Universales.

In [ ]:
# SQRT
# SIN
# CEIL
# FLOOR
# LOG

import numpy as np

values = np.array([[48.32172375, 24.89651106, 77.49724241],
               [77.8184191, 22.54051494, 65.11282444],
               [5.54960482, 59.06720303, 62.52817198]])

np.sqrt(values) # sqrt raiz cuadrada de cada número

np.sin(values)  # seno

np.ceil(values) # redondear hacia arriba

np.floor(values)  # redondear hacia abajo

np.log(values)  # logaritmo

array([[3.87788123, 3.21472768, 4.35024235],
       [4.35437815, 3.11531435, 4.17612153],
       [1.71372672, 4.07867583, 4.13561721]])

Funciones aplicadas por columna

In [ ]:
values = np.array([[8, 2, 7],
                  [2, 0, 6],
                  [6, 3, 4]])

np.sum(values, axis=0) #  suma por columnas

np.sum(values, axis=1)  # suma por filas

np.prod(values, axis=0) # producto por columnas

np.prod(values, axis=1) # producto por filas

array([112,   0,  72])