In [ ]:
# MEAN
# STD
# MEDIAN
import numpy as np

dist = np.array([[-6.79006504, -0.01579498, -0.3298951, -5.30598975],
                 [3.10720923, -4.09625791, -760624152, 2.3454259, 9.23399023],
                 [-7.4394269, -9.68427195, 3.04248586, -5.9843767, 1.536578],
                 [3.33953286, -8.41584411, -9.530274, -2.42827813, -7.34843663],
                 [7.1508544, 5.51727548, -3.20216834, -5.00154367, -7.15715252]])

np.mean(dist) # calcular la media, suma todos los elementos dividido por la misma cantidad de elementos

np.std(dist)  # calcular la desviación tipica

np.median(dist) # calcular la mediana

<ipython-input-1-25e93428d18c>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  dist = np.array([[-6.79006504, -0.01579498, -0.3298951, -5.30598975],


TypeError: ignored

Encontrar los máximos o minimos en el manejo de datos:

In [ ]:
# MAX
# MIN

values = np.array([[66, 54, 33, 15, 58],
                   [55, 46, 39, 16, 38],
                   [73, 75, 79, 25, 83],
                   [81, 30, 22, 32, 8],
                   [92, 25, 82, 10, 90]])

np.min(values) # el valor minimo de mi array

np.min(values, axis=0) # valor minimo de cada columna

np.min(values, axis=1) # valor minimo de cada fila

np.max(values)

np.max(values, axis=0) #valor máximo de cada columna


array([92, 75, 82, 32, 90])

Valores máximos y minimos por indice (posición):

In [ ]:
values = np.array([[66, 54, 33, 15, 58],
                   [55, 46, 39, 16, 38],
                   [73, 75, 79, 25, 83],
                   [81, 30, 22, 32, 8],
                   [92, 25, 82, 10, 90]])

idx = np.argmax(values, axis=0) # valor maximo por columna por posición de la columna

values[idx, range(values.shape[1])] # los valores de idx evaluando cantidad de columnas con range indico fila

array([92, 75, 82, 32, 90])

Vectorizando funciones:

In [ ]:
# NP.VECTORIZE

#EJERCICIO: implementar una función que realice un cálculo entre 2 matrices (a y b).
# Con NP.VECTRORIZE podemos mejorar el rendimiento de la función que hemos diseñado, enfocado al procesamiento de arrays numéricos



import numpy as np
import random

a = np.random.randint(-100, 100, size= (3000, 3000))
b = np.random.randint(-100, 100, size= (3000, 3000))

@np.vectorize
def customf(a,b):
  if a > b:
    return a + b
  elif a < b:
    return a - b
  else:
    return 0

print(a,b)

[[-17 -25 -27 ... -92 -96  80]
 [-21  58  37 ... -44 -58 -83]
 [-78 -31  43 ...  71  31  37]
 ...
 [-55  -3 -23 ... -71  24 -28]
 [ 13  83  29 ...  25  42 -18]
 [-33  93  83 ...  29  91 -68]] [[  8  14 -44 ... -79 -33  96]
 [-71 -24  54 ... -68  -7 -95]
 [-69  83 -54 ...  75  36 -68]
 ...
 [-94  -5 -44 ... -99  56  55]
 [-24  -5 -32 ...   7 -13 -41]
 [-78  66   8 ... -75  27 -68]]
