Numpy

Instalación: $ pip install numpy /n
Importar: import numpy as np

In [ ]:
import numpy as np

x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


Obteniendo información sobre el array:

In [ ]:
# ARRAY

x=np.array([1,2,3,4,5]) # un array es un vector unidimensional

print(x.ndim) #obteniendo dimensión

print(x.size) #obteniendo tamaño total de array

print(x.shape) #obteniendo forma

print(x.dtype) #obteniendo tipo de sus elementos

1
5
(5,)
int64


Tipos de datos: NumPy entiende por defecto que INT hace referencia a np.int64 y que float hace referencia a np.float64

In [ ]:
a= np.array(range(10))
print(a)

print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


Sin embargo podemos especificar el tipo de datos que nos interesa para optimizar la memoria ocupada:

In [ ]:
b= np.array(range(10), dtype='int32') #int32 hace referencia a np.int32
print(b)

[0 1 2 3 4 5 6 7 8 9]


ndarray vs list: el uso de ndarray frente a list está justificado por cuestiones de rendimiento. Ejemplo sumar 10 millones de valores enteros

In [ ]:
array_as_list= list(range(int(10e6)))
array_as_ndarray= np.array(array_as_list)

%timeit sum(array_as_list)
%timeit array_as_ndarray.sum()

87.9 ms ± 7.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
10.8 ms ± 1.62 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


Convertir un ndarray a lista: se puede convertir a listar cualquier ndarray mediante el método tolist()

In [ ]:
# TOLIST

a= np.array([10,20,30])
print(a)
print(type(a))

b= a.tolist() #convierto un ndarray a lista con método tolist
print(b)
print(type(b)) #verifico con type que tipo de dato es: efectivamente cambió a una lista

[10 20 30]
<class 'numpy.ndarray'>
[10, 20, 30]
<class 'list'>


Rango de valores: NumPy tiene una función llamada np.**arange()** cuyo comportamiento es análogo a la función range()

In [ ]:
# ARANGE valores int

#Especificando limite superior:

import numpy as np

ejemplo_1= np.arange(12)
print(ejemplo_1)

#Especificando límite inferior y superior:

ejemplo_2= np.arange(6, 60)
print(ejemplo_2)


#Especificando limite inferior, superior y paso

ejemplo_3= np.arange(6, 60, 3) #star stop step
print(ejemplo_3)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
[ 6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]


In [ ]:
# LINSPACE rango de valores float

#Especificando limite inferior y superior:

import numpy as np

a= np.linspace(6, 60)
print(a)

b= np.linspace(6, 60, 20) # especifica limite inferior, superior y total de elementos que quiero
print(b)

[ 6.          7.10204082  8.20408163  9.30612245 10.40816327 11.51020408
 12.6122449  13.71428571 14.81632653 15.91836735 17.02040816 18.12244898
 19.2244898  20.32653061 21.42857143 22.53061224 23.63265306 24.73469388
 25.83673469 26.93877551 28.04081633 29.14285714 30.24489796 31.34693878
 32.44897959 33.55102041 34.65306122 35.75510204 36.85714286 37.95918367
 39.06122449 40.16326531 41.26530612 42.36734694 43.46938776 44.57142857
 45.67346939 46.7755102  47.87755102 48.97959184 50.08163265 51.18367347
 52.28571429 53.3877551  54.48979592 55.59183673 56.69387755 57.79591837
 58.89795918 60.        ]
[ 6.          8.84210526 11.68421053 14.52631579 17.36842105 20.21052632
 23.05263158 25.89473684 28.73684211 31.57894737 34.42105263 37.26315789
 40.10526316 42.94736842 45.78947368 48.63157895 51.47368421 54.31578947
 57.15789474 60.        ]


Valores aleatorios enteros

In [ ]:
# RANDINT

import numpy as np

a= np.random.randint(3, 30) # numero int aleatorio entre 3 y 29
print(a)

b= np.random.randint(3, 30, size=9) #vector entre 3 y 29 que contenga 9 elementos
print(b)

c= np.random.randint(3, 30, size=(3, 3)) #una matriz con 3 columnas y 3 filas
print(c)

11
[13 22 11 26 12 15 14 10 18]
[[27 15 23]
 [23 18 19]
 [17 18 19]]


Valores aleatorios flotantes

In [ ]:
# RANDOM y UNIFORM

import numpy as np

a= np.random.random(9)  #valores aleatorios flotantes
print(a)

b= np.random.uniform(1, 100, size=9) #valores aleatorios flotantes entre 1 y 99 que contenga 9 elementos
print(b)

[0.80049464 0.39998741 0.5135468  0.43545063 0.84319865 0.09450646
 0.34141337 0.88881597 0.52121701]
[15.75064658  6.68604898 61.73953444 60.50734311 50.74791424 70.713184
 77.20165592 23.095329    2.37780215]


Valores generados de una Normal. Distribución en el que generamos un millón de valores usando como parámetros de la distribución 0 o 5

In [ ]:
# NORMAL

import numpy as np

dist= np.random.normal(0, 5, size=1_000_000)
print(dist)

[ 2.42555661 -3.86625454 -1.6062551  ...  0.2855309  -1.81378175
 10.68279447]


Valores generados de una Bernouilli. Muestra Aleatoria: ejemplo en el que generamos una muestra aleatoria de un millón de lanzamientos de una moneda:

In [ ]:
# CHOICE

import numpy as np

coins= np.random.choice(['head', 'tail'], size=1_000_000) # con choice damos 2 parámetros(cara y cruz) con un vector de hasta 1millón de posibilidades
print(coins) #probabilidad 50% a 50%

a= sum(coins == 'head') # suma de la cantidad de veces que salieron los head
print(a)

b= sum(coins == 'tail') # suma de la cantidad de veces que salieron los tail
print(b)


['head' 'tail' 'tail' ... 'head' 'tail' 'head']
499692
500308


Constantes predefinidas en NumPy. NumPy proporciona una seria de constantes predefinidas que facilitan su acceso y reutilización

In [ ]:
import numpy as np

a= np.Inf
print(a)

b= np.nan
print(b)

c= np.e
print(c)

e= np.pi
print(e)

inf
nan
2.718281828459045
3.141592653589793
